version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: TodoUserPass456!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: